server:
  port: 0

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/order_db
    username: dbuser
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  sql:
    init:
      mode: never
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 3000
            readTimeout: 5000
          inventory-service:
            connectTimeout: 2000
            readTimeout: 3000
            loggerLevel: basic

logging:
  level:
    ru.yandex.practicum.order.feign.inventory.InventoryClient: DEBUG
