server:
  port: 0

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/order_db
    username: dbuser
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  sql:
    init:
      mode: never
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          default:
            connectTimeout: 3000
            readTimeout: 5000
          inventory-service:
            connectTimeout: 2000
            readTimeout: 3000
            loggerLevel: basic

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 5
        minimum-number-of-calls: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        ignore-exceptions:
          - feign.FeignException$FeignClientException
  timelimiter:
    configs:
      default:
        timeout-duration: 3s

logging:
  level:
    ru.yandex.practicum.order.feign: DEBUG
