grpc.server.port=59091

collector.kafka.sensors-topic=telemetry.sensors.v1
collector.kafka.hubs-topic=telemetry.hubs.v1

collector.kafka.producer.[bootstrap.servers]=localhost:9092
collector.kafka.producer.[key.serializer]=org.apache.kafka.common.serialization.StringSerializer
collector.kafka.producer.[value.serializer]=ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer
