spring.kafka.bootstrap-servers=localhost:9092
aggregator.kafka.consumer-group=telemetry.aggregator
aggregator.kafka.sensors-topic=telemetry.sensors.v1
aggregator.kafka.snapshots-topic=telemetry.snapshots.v1
aggregator.kafka.poll-timeout=PT1S
