spring.datasource.url=jdbc:postgresql://localhost:5432/telemetry_analyzer
spring.datasource.username=dbuser
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always

analyzer.kafka.hubs-topic=telemetry.hubs.v1
analyzer.kafka.snapshots-topic=telemetry.snapshots.v1
analyzer.kafka.poll-timeout=PT1S

analyzer.kafka.hub-event-consumer.[bootstrap.servers]=localhost:9092
analyzer.kafka.hub-event-consumer.[group.id]=telemetry.analyzer.hubs
analyzer.kafka.hub-event-consumer.[key.deserializer]=org.apache.kafka.common.serialization.StringDeserializer
analyzer.kafka.hub-event-consumer.[value.deserializer]=ru.yandex.practicum.kafka.serializer.HubEventDeserializer
analyzer.kafka.hub-event-consumer.[enable.auto.commit]=false
analyzer.kafka.hub-event-consumer.[auto.offset.reset]=earliest

analyzer.kafka.snapshot-consumer.[bootstrap.servers]=localhost:9092
analyzer.kafka.snapshot-consumer.[group.id]=telemetry.analyzer.snapshots
analyzer.kafka.snapshot-consumer.[key.deserializer]=org.apache.kafka.common.serialization.StringDeserializer
analyzer.kafka.snapshot-consumer.[value.deserializer]=ru.yandex.practicum.kafka.serializer.SensorsSnapshotDeserializer
analyzer.kafka.snapshot-consumer.[enable.auto.commit]=false
analyzer.kafka.snapshot-consumer.[auto.offset.reset]=earliest

grpc.client.hub-router.address=static://localhost:59090
grpc.client.hub-router.enableKeepAlive=true
grpc.client.hub-router.keepAliveWithoutCalls=true
grpc.client.hub-router.negotiationType=plaintext
