spring.kafka.bootstrap-servers=localhost:9092

spring.datasource.url=jdbc:postgresql://localhost:5432/telemetry_analyzer
spring.datasource.username=dbuser
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always

analyzer.kafka.hubs-topic=telemetry.hubs.v1
analyzer.kafka.snapshots-topic=telemetry.snapshots.v1
analyzer.kafka.hub-events-group=telemetry.analyzer.hubs
analyzer.kafka.snapshots-group=telemetry.analyzer.snapshots
analyzer.kafka.poll-timeout=PT1S

grpc.client.hub-router.address=static://localhost:59090
grpc.client.hub-router.enableKeepAlive=true
grpc.client.hub-router.keepAliveWithoutCalls=true
grpc.client.hub-router.negotiationType=plaintext
